apiVersion: v1
kind: Namespace
metadata:
  name: gitops-ocs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-ocs-operator-operator-group
  namespace: gitops-ocs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-ocs-operator
---
